<?php

namespace Tests\AppBundle\Repository;
use PHPUnit\Framework\TestCase;

/**
 * PaymentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMethodRepositoryTest extends TestCase
{
    public function testIndex()
    {
        $this->assertTrue(true);
    }
}