<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByParent($parent = null)
    {
        $query = $this->createQueryBuilder('c');
        if($parent){
            $query->where('c.parentId = :parent')
                ->setParameter('parent', $parent);
        }else{
            $query->where('c.parentId IS NULL');
        }


        return $query->getQuery()->getResult();
    }
}
