<?php

namespace AppBundle\Repository;

/**
 * OperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Dépense
     *
     * @return array
     */
    public function findAllExpenseGroupByCategory($parent = null)
    {
        $query = $this->createQueryBuilder('o');

        $query->select('SUM(o.amound) as amound')
              ->addSelect('c.id as idCategory');

        $query->leftJoin('o.category', 'c');

        $query->where('o.amound < 0');

        $query->groupBy('o.category');

        return $query->getQuery()
                     ->getResult();
    }

    /**
     * Revenu
     *
     * @return array
     */
    public function findAllIncomeGroupByCategory()
    {
    }
}
